// import {DEFAULT_CHAIN} from '@/typescript/types/ContractT';
/*
 * ************************************************************
 * Be sure you use the ContractT type for your contracts!
 * ************************************************************
 * Example:
 * {
 *    name: 'MyContract',
 *    ethers: false, // We start with no ethers instance
 *    address: '0x1234567890',
 *    abi: '[...]',
 *    chainId: DEFAULT_CHAIN,
 *  }
 */
export const Game = {
  address: '0xD45d3e16E107f49216089760c169d93d029A1c9c',
  chainId: 56,
  abi: [
    {
      inputs: [{internalType: 'uint256', name: 'versionNo_', type: 'uint256'}],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    {
      inputs: [
        {internalType: 'address', name: 'have', type: 'address'},
        {internalType: 'address', name: 'want', type: 'address'},
      ],
      name: 'OnlyCoordinatorCanFulfill',
      type: 'error',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: false, internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {indexed: false, internalType: 'uint256', name: 'gameId', type: 'uint256'},
        {indexed: false, internalType: 'address', name: 'loser', type: 'address'},
      ],
      name: 'GameEnded',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: false, internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {indexed: false, internalType: 'uint256', name: 'gameId', type: 'uint256'},
      ],
      name: 'GameStarted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: true, internalType: 'address', name: 'oldOwner', type: 'address'},
        {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
      ],
      name: 'OwnerSet',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: false, internalType: 'uint256', name: 'newTableId', type: 'uint256'},
        {indexed: false, internalType: 'address', name: 'token', type: 'address'},
        {indexed: false, internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {indexed: false, internalType: 'uint32', name: 'max_palyers', type: 'uint32'},
        {indexed: false, internalType: 'uint32', name: 'duration', type: 'uint32'},
        {indexed: false, internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
      ],
      name: 'TableCreated',
      type: 'event',
    },
    {
      inputs: [],
      name: 'RE_REQUEST_TIME',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'chainlinkFeesRecipient',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
      name: 'changeOwner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
      ],
      name: 'createTable',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'amount', type: 'uint256'},
      ],
      name: 'donateToGamePot',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'endGame',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'feeRecipient',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'gameNonce',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      name: 'games',
      outputs: [
        {internalType: 'bool', name: 'hasEnded', type: 'bool'},
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address', name: 'loser', type: 'address'},
        {internalType: 'uint256', name: 'pot', type: 'uint256'},
        {internalType: 'uint256', name: 'startTime', type: 'uint256'},
        {internalType: 'uint256', name: 'requestTime', type: 'uint256'},
        {internalType: 'uint256', name: 'request', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'getGameInfo',
      outputs: [
        {internalType: 'bool', name: 'gameEnded', type: 'bool'},
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address[]', name: 'players', type: 'address[]'},
        {internalType: 'address', name: 'loser', type: 'address'},
        {internalType: 'uint256', name: 'pot', type: 'uint256'},
        {internalType: 'uint256', name: 'startTime', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'getLoserForGame',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getOwner',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'getPlayersForGame',
      outputs: [{internalType: 'address[]', name: '', type: 'address[]'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'getPlayersForTable',
      outputs: [{internalType: 'address[]', name: '', type: 'address[]'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'getTableInfo',
      outputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
        {internalType: 'uint256', name: 'gameID', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'history',
      outputs: [{internalType: 'contract IHistory', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'gameId', type: 'uint256'},
        {internalType: 'address', name: 'player', type: 'address'},
      ],
      name: 'isPlayerInGame',
      outputs: [{internalType: 'bool', name: '', type: 'bool'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address', name: 'player', type: 'address'},
      ],
      name: 'isPlayerInTable',
      outputs: [{internalType: 'bool', name: '', type: 'bool'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'ref', type: 'uint256'},
      ],
      name: 'joinGame',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listGameIDs',
      outputs: [{internalType: 'uint256[]', name: 'gameIDs', type: 'uint256[]'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listTableAndGamesInfo',
      outputs: [
        {internalType: 'address[]', name: 'gameTokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'uint32[]', name: 'max_playerss', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'durations', type: 'uint32[]'},
        {internalType: 'uint256[]', name: 'numberOfPlayers', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'pots', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'gameIDs', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'startTimes', type: 'uint256[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listTableInfo',
      outputs: [
        {internalType: 'address[]', name: 'gameTokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'uint32[]', name: 'max_playerss', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'durations', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'gasToCallRandoms', type: 'uint32[]'},
        {internalType: 'uint256[]', name: 'gameIDs', type: 'uint256[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'minBuyInGas',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'platformFee',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'requestId', type: 'uint256'},
        {internalType: 'uint256[]', name: 'randomWords', type: 'uint256[]'},
      ],
      name: 'rawFulfillRandomWords',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'reRequestWords',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'refundGame',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'removeTable',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'newBuyIn', type: 'uint256'},
      ],
      name: 'setBuyIn',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newChainlinkFeesRecipient', type: 'address'}],
      name: 'setChainlinkFeesRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
      ],
      name: 'setDuration',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newRecipient', type: 'address'}],
      name: 'setFeeRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'newGas', type: 'uint32'},
      ],
      name: 'setGasToCallRandom',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'bytes32', name: 'newHash', type: 'bytes32'}],
      name: 'setKeyHash',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'maxPlayers', type: 'uint32'},
      ],
      name: 'setMaxPlayers',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'weiValue', type: 'uint256'}],
      name: 'setMinBuyInGas',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'newFee', type: 'uint256'}],
      name: 'setPlatformFee',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'newTime', type: 'uint256'}],
      name: 'setReRequestTime',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint64', name: 'subscriptionID', type: 'uint64'}],
      name: 'setSubscriptionID',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address', name: 'token', type: 'address'},
      ],
      name: 'setToken',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'newFee', type: 'uint256'},
      ],
      name: 'setTokenFee',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'address', name: 'newRecipient', type: 'address'},
      ],
      name: 'setTokenFeeRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'tableNonce',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      name: 'tables',
      outputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
        {internalType: 'uint256', name: 'gameID', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'timeLeftInGame',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'timeToRerequest',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'token', type: 'address'}],
      name: 'tokenBalance',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: '', type: 'address'}],
      name: 'tokens',
      outputs: [
        {internalType: 'bool', name: 'isApproved', type: 'bool'},
        {internalType: 'uint256', name: 'fee', type: 'uint256'},
        {internalType: 'address', name: 'feeRecipient', type: 'address'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'versionNo',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'amount', type: 'uint256'}],
      name: 'withdrawETH',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'amount', type: 'uint256'},
      ],
      name: 'withdrawToken',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ],
} as const;

export const History = {
  address: '0x764F174c3969233Bb230a2dFF12c86102D913409',
  chainId: 56,
  abi: [
    {
      anonymous: false,
      inputs: [
        {indexed: true, internalType: 'address', name: 'oldOwner', type: 'address'},
        {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
      ],
      name: 'OwnerSet',
      type: 'event',
    },
    {
      inputs: [
        {internalType: 'address', name: 'user', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'gameId', type: 'uint256'},
        {internalType: 'uint256', name: 'versionNo', type: 'uint256'},
      ],
      name: 'addData',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
      name: 'changeOwner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'game',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: '', type: 'address'},
        {internalType: 'uint256', name: '', type: 'uint256'},
      ],
      name: 'gameIdToUserNonce',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: '', type: 'address'},
        {internalType: 'uint256', name: '', type: 'uint256'},
      ],
      name: 'games',
      outputs: [
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'gameId', type: 'uint256'},
        {internalType: 'uint256', name: 'time', type: 'uint256'},
        {internalType: 'uint256', name: 'versionNo', type: 'uint256'},
        {internalType: 'bool', name: 'lost', type: 'bool'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getOwner',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'user', type: 'address'}],
      name: 'getUserData',
      outputs: [
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'address[]', name: 'tokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'gameIds', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'times', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'versionNos', type: 'uint256[]'},
        {internalType: 'bool[]', name: 'losts', type: 'bool[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'user', type: 'address'},
        {internalType: 'uint256', name: 'start', type: 'uint256'},
        {internalType: 'uint256', name: 'end', type: 'uint256'},
      ],
      name: 'getUserDataPaginated',
      outputs: [
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'address[]', name: 'tokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'gameIds', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'times', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'versionNos', type: 'uint256[]'},
        {internalType: 'bool[]', name: 'losts', type: 'bool[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newGame', type: 'address'}],
      name: 'setGame',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'user', type: 'address'},
        {internalType: 'uint256', name: 'gameId', type: 'uint256'},
      ],
      name: 'setLost',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ],
} as const;

export const WinnerTakesAll = {
  address: '0x736f1923667605A872274178530F4b256731ec55',
  chainId: 56,
  abi: [
    {
      inputs: [{internalType: 'uint256', name: 'versionNo_', type: 'uint256'}],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    {
      inputs: [
        {internalType: 'address', name: 'have', type: 'address'},
        {internalType: 'address', name: 'want', type: 'address'},
      ],
      name: 'OnlyCoordinatorCanFulfill',
      type: 'error',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: false, internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {indexed: false, internalType: 'uint256', name: 'gameId', type: 'uint256'},
        {indexed: false, internalType: 'address', name: 'winner', type: 'address'},
      ],
      name: 'GameEnded',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: false, internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {indexed: false, internalType: 'uint256', name: 'gameId', type: 'uint256'},
      ],
      name: 'GameStarted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: true, internalType: 'address', name: 'oldOwner', type: 'address'},
        {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
      ],
      name: 'OwnerSet',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: false, internalType: 'uint256', name: 'newTableId', type: 'uint256'},
        {indexed: false, internalType: 'address', name: 'token', type: 'address'},
        {indexed: false, internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {indexed: false, internalType: 'uint32', name: 'max_palyers', type: 'uint32'},
        {indexed: false, internalType: 'uint32', name: 'duration', type: 'uint32'},
        {indexed: false, internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
      ],
      name: 'TableCreated',
      type: 'event',
    },
    {
      inputs: [],
      name: 'RE_REQUEST_TIME',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'chainlinkFeesRecipient',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
      name: 'changeOwner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
      ],
      name: 'createTable',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'amount', type: 'uint256'},
      ],
      name: 'donateToGamePot',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'endGame',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'feeRecipient',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'gameNonce',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      name: 'games',
      outputs: [
        {internalType: 'bool', name: 'hasEnded', type: 'bool'},
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address', name: 'winner', type: 'address'},
        {internalType: 'uint256', name: 'pot', type: 'uint256'},
        {internalType: 'uint256', name: 'startTime', type: 'uint256'},
        {internalType: 'uint256', name: 'requestTime', type: 'uint256'},
        {internalType: 'uint256', name: 'request', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'getGameInfo',
      outputs: [
        {internalType: 'bool', name: 'gameEnded', type: 'bool'},
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address[]', name: 'players', type: 'address[]'},
        {internalType: 'address', name: 'winner', type: 'address'},
        {internalType: 'uint256', name: 'pot', type: 'uint256'},
        {internalType: 'uint256', name: 'startTime', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getOwner',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'getPlayersForGame',
      outputs: [{internalType: 'address[]', name: '', type: 'address[]'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'getPlayersForTable',
      outputs: [{internalType: 'address[]', name: '', type: 'address[]'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'getTableInfo',
      outputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
        {internalType: 'uint256', name: 'gameID', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getTableTokenData',
      outputs: [
        {internalType: 'string[]', name: 'names', type: 'string[]'},
        {internalType: 'string[]', name: 'symbols', type: 'string[]'},
        {internalType: 'uint8[]', name: 'decimals', type: 'uint8[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'getWinnerForGame',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'history',
      outputs: [{internalType: 'contract IHistory', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'gameId', type: 'uint256'},
        {internalType: 'address', name: 'player', type: 'address'},
      ],
      name: 'isPlayerInGame',
      outputs: [{internalType: 'bool', name: '', type: 'bool'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address', name: 'player', type: 'address'},
      ],
      name: 'isPlayerInTable',
      outputs: [{internalType: 'bool', name: '', type: 'bool'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'ref', type: 'uint256'},
      ],
      name: 'joinGame',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listGameIDs',
      outputs: [{internalType: 'uint256[]', name: 'gameIDs', type: 'uint256[]'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listGamesPlayedPerTable',
      outputs: [{internalType: 'uint112[]', name: 'numGamesPlayed', type: 'uint112[]'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listTableAndGamesInfo',
      outputs: [
        {internalType: 'address[]', name: 'gameTokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'uint32[]', name: 'max_playerss', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'durations', type: 'uint32[]'},
        {internalType: 'uint256[]', name: 'numberOfPlayers', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'pots', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'gameIDs', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'startTimes', type: 'uint256[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listTableInfo',
      outputs: [
        {internalType: 'address[]', name: 'gameTokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'uint32[]', name: 'max_playerss', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'durations', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'gasToCallRandoms', type: 'uint32[]'},
        {internalType: 'uint256[]', name: 'gameIDs', type: 'uint256[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'minBuyInGas',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'platformFee',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'requestId', type: 'uint256'},
        {internalType: 'uint256[]', name: 'randomWords', type: 'uint256[]'},
      ],
      name: 'rawFulfillRandomWords',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'reRequestWords',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'refundGame',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'removeTable',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'newBuyIn', type: 'uint256'},
      ],
      name: 'setBuyIn',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newChainlinkFeesRecipient', type: 'address'}],
      name: 'setChainlinkFeesRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
      ],
      name: 'setDuration',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newRecipient', type: 'address'}],
      name: 'setFeeRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'newGas', type: 'uint32'},
      ],
      name: 'setGasToCallRandom',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'bytes32', name: 'newHash', type: 'bytes32'}],
      name: 'setKeyHash',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'maxPlayers', type: 'uint32'},
      ],
      name: 'setMaxPlayers',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'weiValue', type: 'uint256'}],
      name: 'setMinBuyInGas',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'newFee', type: 'uint256'}],
      name: 'setPlatformFee',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'newTime', type: 'uint256'}],
      name: 'setReRequestTime',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint64', name: 'subscriptionID', type: 'uint64'}],
      name: 'setSubscriptionID',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address', name: 'token', type: 'address'},
      ],
      name: 'setToken',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'newFee', type: 'uint256'},
      ],
      name: 'setTokenFee',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'address', name: 'newRecipient', type: 'address'},
      ],
      name: 'setTokenFeeRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'tableNonce',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      name: 'tables',
      outputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
        {internalType: 'uint256', name: 'gameID', type: 'uint256'},
        {internalType: 'uint112', name: 'numGamesPlayed', type: 'uint112'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'timeLeftInGame',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'timeToRerequest',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'token', type: 'address'}],
      name: 'tokenBalance',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: '', type: 'address'}],
      name: 'tokens',
      outputs: [
        {internalType: 'bool', name: 'isApproved', type: 'bool'},
        {internalType: 'uint256', name: 'fee', type: 'uint256'},
        {internalType: 'address', name: 'feeRecipient', type: 'address'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'versionNo',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'amount', type: 'uint256'}],
      name: 'withdrawETH',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'amount', type: 'uint256'},
      ],
      name: 'withdrawToken',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ],
} as const;

export const WinnerTakesAllHistory = {
  address: '0xe73b33087370C198F9DF2A185fed64416775c4aD',
  chainId: 56,
  abi: [
    {
      anonymous: false,
      inputs: [
        {indexed: true, internalType: 'address', name: 'oldOwner', type: 'address'},
        {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
      ],
      name: 'OwnerSet',
      type: 'event',
    },
    {
      inputs: [
        {internalType: 'address', name: 'user', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'gameId', type: 'uint256'},
        {internalType: 'uint256', name: 'versionNo', type: 'uint256'},
      ],
      name: 'addData',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
      name: 'changeOwner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'game',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: '', type: 'address'},
        {internalType: 'uint256', name: '', type: 'uint256'},
      ],
      name: 'gameIdToUserNonce',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: '', type: 'address'},
        {internalType: 'uint256', name: '', type: 'uint256'},
      ],
      name: 'games',
      outputs: [
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'gameId', type: 'uint256'},
        {internalType: 'uint256', name: 'time', type: 'uint256'},
        {internalType: 'uint256', name: 'versionNo', type: 'uint256'},
        {internalType: 'bool', name: 'won', type: 'bool'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getOwner',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'user', type: 'address'}],
      name: 'getUserData',
      outputs: [
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'address[]', name: 'tokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'gameIds', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'times', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'versionNos', type: 'uint256[]'},
        {internalType: 'bool[]', name: 'wins', type: 'bool[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'user', type: 'address'},
        {internalType: 'uint256', name: 'start', type: 'uint256'},
        {internalType: 'uint256', name: 'end', type: 'uint256'},
      ],
      name: 'getUserDataPaginated',
      outputs: [
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'address[]', name: 'tokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'gameIds', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'times', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'versionNos', type: 'uint256[]'},
        {internalType: 'bool[]', name: 'wins', type: 'bool[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newGame', type: 'address'}],
      name: 'setGame',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'user', type: 'address'},
        {internalType: 'uint256', name: 'gameId', type: 'uint256'},
      ],
      name: 'setWinner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ],
} as const;
