// import {DEFAULT_CHAIN} from '@/typescript/types/ContractT';
/*
 * ************************************************************
 * Be sure you use the ContractT type for your contracts!
 * ************************************************************
 * Example:
 * {
 *    name: 'MyContract',
 *    ethers: false, // We start with no ethers instance
 *    address: '0x1234567890',
 *    abi: '[...]',
 *    chainId: DEFAULT_CHAIN,
 *  }
 */
export const Game = {
  address: '0x3940AC8796d93dacF425031D009f4C88C8E8415F',
  chainId: 56,
  abi: [
    {inputs: [], stateMutability: 'nonpayable', type: 'constructor'},
    {inputs: [{internalType: 'int256', name: 'linkWei', type: 'int256'}], name: 'InvalidLinkWeiPrice', type: 'error'},
    {
      inputs: [
        {internalType: 'address', name: 'have', type: 'address'},
        {internalType: 'address', name: 'want', type: 'address'},
      ],
      name: 'OnlyCoordinatorCanFulfill',
      type: 'error',
    },
    {inputs: [], name: 'WrongGasValueToCoverFee', type: 'error'},
    {
      anonymous: false,
      inputs: [
        {indexed: true, internalType: 'address', name: 'token', type: 'address'},
        {indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256'},
      ],
      name: 'DistributeTokenVRFFees',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: false, internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {indexed: false, internalType: 'uint256', name: 'gameId', type: 'uint256'},
      ],
      name: 'GameStarted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: true, internalType: 'address', name: 'oldOwner', type: 'address'},
        {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
      ],
      name: 'OwnerSet',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {indexed: false, internalType: 'uint256', name: 'newTableId', type: 'uint256'},
        {indexed: false, internalType: 'address', name: 'token', type: 'address'},
        {indexed: false, internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {indexed: false, internalType: 'uint32', name: 'max_palyers', type: 'uint32'},
        {indexed: false, internalType: 'uint32', name: 'duration', type: 'uint32'},
        {indexed: false, internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
      ],
      name: 'TableCreated',
      type: 'event',
    },
    {
      inputs: [],
      name: 'RE_REQUEST_TIME',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'chainlinkFeesRecipient',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
      name: 'changeOwner',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
      ],
      name: 'createTable',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'destroyGame',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'donateToPot',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'endGame',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'feeRecipient',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'gameNonce',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      name: 'games',
      outputs: [
        {internalType: 'bool', name: 'hasEnded', type: 'bool'},
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'pot', type: 'uint256'},
        {internalType: 'uint256', name: 'startTime', type: 'uint256'},
        {internalType: 'address', name: 'initiator', type: 'address'},
        {internalType: 'uint256', name: 'requestTime', type: 'uint256'},
        {internalType: 'uint256', name: 'request', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'getAdjustedPot',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'getGameInfo',
      outputs: [
        {internalType: 'bool', name: 'gameEnded', type: 'bool'},
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address[]', name: 'players', type: 'address[]'},
        {internalType: 'uint256', name: 'pot', type: 'uint256'},
        {internalType: 'uint256', name: 'startTime', type: 'uint256'},
        {internalType: 'uint256', name: 'adjustedPot', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getOwner',
      outputs: [{internalType: 'address', name: '', type: 'address'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'getTableInfo',
      outputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
        {internalType: 'uint256', name: 'gameID', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'ref', type: 'uint256'},
      ],
      name: 'joinGame',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listTableAndGamesInfo',
      outputs: [
        {internalType: 'address[]', name: 'gameTokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'uint32[]', name: 'max_playerss', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'durations', type: 'uint32[]'},
        {internalType: 'uint256[]', name: 'numberOfPlayers', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'pots', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'adjustedPots', type: 'uint256[]'},
        {internalType: 'uint256[]', name: 'startTimes', type: 'uint256[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'listTableInfo',
      outputs: [
        {internalType: 'address[]', name: 'gameTokens', type: 'address[]'},
        {internalType: 'uint256[]', name: 'buyIns', type: 'uint256[]'},
        {internalType: 'uint32[]', name: 'max_playerss', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'durations', type: 'uint32[]'},
        {internalType: 'uint32[]', name: 'gasToCallRandoms', type: 'uint32[]'},
        {internalType: 'uint256[]', name: 'gameIDs', type: 'uint256[]'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'minBuyInGas',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'platformFee',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'requestId', type: 'uint256'},
        {internalType: 'uint256[]', name: 'randomWords', type: 'uint256[]'},
      ],
      name: 'rawFulfillRandomWords',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'reRequestWords',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'removeTable',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'newBuyIn', type: 'uint256'},
      ],
      name: 'setBuyIn',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newChainlinkFeesRecipient', type: 'address'}],
      name: 'setChainlinkFeesRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
      ],
      name: 'setDuration',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'newRecipient', type: 'address'}],
      name: 'setFeeRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'newGas', type: 'uint32'},
      ],
      name: 'setGasToCallRandom',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'bytes32', name: 'newHash', type: 'bytes32'}],
      name: 'setKeyHash',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint32', name: 'maxPlayers', type: 'uint32'},
      ],
      name: 'setMaxPlayers',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'weiValue', type: 'uint256'}],
      name: 'setMinBuyInGas',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'newFee', type: 'uint256'}],
      name: 'setPlatformFee',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'newTime', type: 'uint256'}],
      name: 'setReRequestTime',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint64', name: 'subscriptionID', type: 'uint64'}],
      name: 'setSubscriptionID',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'address', name: 'token', type: 'address'},
      ],
      name: 'setToken',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'newFee', type: 'uint256'},
      ],
      name: 'setTokenFee',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'address', name: 'newRecipient', type: 'address'},
      ],
      name: 'setTokenFeeRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'uint256', name: 'tableId', type: 'uint256'},
        {internalType: 'uint256', name: 'ref', type: 'uint256'},
      ],
      name: 'startAndJoin',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'startGame',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'tableNonce',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      name: 'tables',
      outputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'buyIn', type: 'uint256'},
        {internalType: 'uint32', name: 'max_players', type: 'uint32'},
        {internalType: 'uint32', name: 'duration', type: 'uint32'},
        {internalType: 'uint32', name: 'gasToCallRandom', type: 'uint32'},
        {internalType: 'uint256', name: 'gameID', type: 'uint256'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'tableId', type: 'uint256'}],
      name: 'timeLeftInGame',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'gameId', type: 'uint256'}],
      name: 'timeToRerequest',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: 'token', type: 'address'}],
      name: 'tokenBalance',
      outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'address', name: '', type: 'address'}],
      name: 'tokens',
      outputs: [
        {internalType: 'bool', name: 'isApproved', type: 'bool'},
        {internalType: 'uint256', name: 'fee', type: 'uint256'},
        {internalType: 'address', name: 'feeRecipient', type: 'address'},
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{internalType: 'uint256', name: 'amount', type: 'uint256'}],
      name: 'withdrawETH',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {internalType: 'address', name: 'token', type: 'address'},
        {internalType: 'uint256', name: 'amount', type: 'uint256'},
      ],
      name: 'withdrawToken',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ],
} as const;
